local M = {}

function M.setup(c)
  local none = "NONE"

  -- stylua: ignore
  local groups = {
    -- UI
    Normal          = { fg = c.fg,       bg = c.bg },
    NormalFloat     = { fg = c.fg,       bg = c.bgdark },
    NormalNC        = { fg = c.fg,       bg = c.bg },
    ColorColumn     = {                  bg = c.bgdark },
    CursorLine      = {                  bg = c.subtle },
    CursorColumn    = {                  bg = c.subtle },
    CursorLineNr    = { fg = c.yellow },
    LineNr          = { fg = c.comment },
    SignColumn      = { fg = c.comment },
    StatusLine      = {                  bg = c.bglighter, bold = true },
    StatusLineNC    = {                  bg = c.bglight },
    TabLine         = { fg = c.comment,  bg = c.bgdark },
    TabLineFill     = {                  bg = c.bgdark },
    TabLineSel      = { fg = c.fg,       bg = c.bg },
    WinSeparator    = { fg = c.comment,  bg = c.bgdark },
    VertSplit       = { fg = c.comment,  bg = c.bgdark },
    Folded          = { fg = c.comment,  bg = c.bgdark },
    FoldColumn      = { fg = c.comment },
    Directory       = { fg = c.purple,   bold = true },
    Visual          = {                  bg = c.selection },
    VisualNOS       = {                  bg = c.selection },
    Pmenu           = {                  bg = c.bgdark },
    PmenuSbar       = {                  bg = c.bgdark },
    PmenuSel        = {                  bg = c.selection },
    PmenuThumb      = {                  bg = c.selection },
    PmenuMatch      = { fg = c.cyan,     bg = c.bgdark },
    PmenuMatchSel   = { fg = c.cyan,     bg = c.selection },
    WildMenu        = { fg = c.bg,       bg = c.purple, bold = true },
    Search          = { fg = c.green,    reverse = true },
    IncSearch       = { fg = c.orange,   reverse = true },
    CurSearch       = { fg = c.orange,   reverse = true },
    MatchParen      = { fg = c.green,    underline = true },
    Conceal         = { fg = c.cyan },
    NonText         = { fg = c.subtle },
    SpecialKey      = { fg = c.red },
    Title           = { fg = c.green,    bold = true },
    Question        = { fg = c.fg,       bold = true },
    MoreMsg         = { fg = c.fg,       bold = true },
    ErrorMsg        = { fg = c.fg,       bg = c.red },
    WarningMsg      = { fg = c.fg,       bg = c.orange },
    DiffAdd         = { fg = c.green },
    DiffChange      = { fg = c.orange },
    DiffDelete      = { fg = c.red,      bg = c.bgdark },
    DiffText        = { fg = c.bg,       bg = c.orange },
    Added           = { fg = c.green },
    Changed         = { fg = c.orange },
    Removed         = { fg = c.red },

    -- Syntax
    Comment         = { fg = c.comment,  italic = true },
    Constant        = { fg = c.purple },
    String          = { fg = c.yellow },
    Character       = { fg = c.pink },
    Number          = { fg = c.purple },
    Boolean         = { fg = c.purple },
    Float           = { fg = c.purple },
    Identifier      = { fg = c.fg },
    Function        = { fg = c.green },
    Statement       = { fg = c.pink },
    Conditional     = { fg = c.pink },
    Repeat          = { fg = c.pink },
    Label           = { fg = c.pink },
    Operator        = { fg = c.pink },
    Keyword         = { fg = c.pink },
    Exception       = { fg = c.pink },
    PreProc         = { fg = c.pink },
    Include         = { fg = c.pink },
    Define          = { fg = c.pink },
    Macro           = { fg = c.pink },
    PreCondit       = { fg = c.pink },
    StorageClass    = { fg = c.pink },
    Structure       = { fg = c.pink },
    Typedef         = { fg = c.pink },
    Type            = { fg = c.cyan,     italic = true },
    Special         = { fg = c.pink },
    SpecialComment  = { fg = c.cyan,     italic = true },
    Tag             = { fg = c.cyan },
    Delimiter       = { fg = c.fg },
    Underlined      = { fg = c.fg,       underline = true },
    Todo            = { fg = c.cyan,     bg = c.bg, bold = true, reverse = true },
    Error           = { fg = c.red,      sp = c.red },
    SpellBad        = { undercurl = true, sp = c.red },
    SpellLocal      = { undercurl = true, sp = c.orange },
    SpellCap        = { undercurl = true, sp = c.cyan },
    SpellRare       = { undercurl = true, sp = c.cyan },

    -- Diagnostics
    DiagnosticError            = { fg = c.red },
    DiagnosticWarn             = { fg = c.orange },
    DiagnosticInfo             = { fg = c.cyan },
    DiagnosticHint             = { fg = c.cyan },
    DiagnosticUnderlineError   = { undercurl = true, sp = c.red },
    DiagnosticUnderlineWarn    = { undercurl = true, sp = c.orange },
    DiagnosticUnderlineInfo    = { undercurl = true, sp = c.cyan },
    DiagnosticUnderlineHint    = { undercurl = true, sp = c.cyan },
    DiagnosticVirtualTextError = { fg = c.red },
    DiagnosticVirtualTextWarn  = { fg = c.orange },
    DiagnosticVirtualTextInfo  = { fg = c.cyan },
    DiagnosticVirtualTextHint  = { fg = c.cyan },

    -- LSP
    LspReferenceText          = { bg = c.selection },
    LspReferenceRead          = { bg = c.selection },
    LspReferenceWrite         = { bg = c.selection },
    LspInlayHint              = { fg = c.comment, bg = c.bgdark },
    ["@lsp.type.class"]       = { fg = c.cyan },
    ["@lsp.type.decorator"]   = { fg = c.green },
    ["@lsp.type.enum"]        = { fg = c.cyan },
    ["@lsp.type.enumMember"]  = { fg = c.purple },
    ["@lsp.type.function"]    = { fg = c.green },
    ["@lsp.type.interface"]   = { fg = c.cyan },
    ["@lsp.type.macro"]       = { fg = c.cyan },
    ["@lsp.type.method"]      = { fg = c.green },
    ["@lsp.type.namespace"]   = { fg = c.cyan },
    ["@lsp.type.parameter"]   = { fg = c.orange, italic = true },
    ["@lsp.type.property"]    = { fg = c.orange },
    ["@lsp.type.struct"]      = { fg = c.cyan },
    ["@lsp.type.type"]        = { fg = c.cyan, italic = true },
    ["@lsp.type.variable"]    = { fg = c.fg },

    -- Treesitter
    ["@punctuation.delimiter"]    = { fg = c.fg },
    ["@punctuation.bracket"]      = { fg = c.fg },
    ["@punctuation.special"]      = { fg = c.pink },
    ["@constant"]                 = { fg = c.purple },
    ["@constant.builtin"]         = { fg = c.purple },
    ["@constant.macro"]           = { fg = c.pink },
    ["@string"]                   = { fg = c.yellow },
    ["@string.regexp"]            = { fg = c.red },
    ["@string.escape"]            = { fg = c.pink },
    ["@string.special"]           = { fg = c.pink },
    ["@string.special.symbol"]    = { fg = c.purple },
    ["@string.special.url"]       = { fg = c.fg, underline = true },
    ["@annotation"]               = { fg = c.yellow },
    ["@attribute"]                = { fg = c.green, italic = true },
    ["@namespace"]                = { fg = c.fg },
    ["@module"]                   = { fg = c.fg },
    ["@module.builtin"]           = { fg = c.pink },
    ["@function.builtin"]         = { fg = c.cyan },
    ["@function"]                 = { fg = c.green },
    ["@function.macro"]           = { fg = c.green },
    ["@parameter"]                = { fg = c.orange, italic = true },
    ["@field"]                    = { fg = c.orange },
    ["@property"]                 = { fg = c.fg },
    ["@constructor"]              = { fg = c.cyan },
    ["@label"]                    = { fg = c.purple, italic = true },
    ["@keyword"]                  = { fg = c.pink },
    ["@keyword.function"]         = { fg = c.pink },
    ["@keyword.operator"]         = { fg = c.pink },
    ["@exception"]                = { fg = c.purple },
    ["@operator"]                 = { fg = c.pink },
    ["@type"]                     = { fg = c.cyan, italic = true },
    ["@type.builtin"]             = { fg = c.pink },
    ["@variable"]                 = { fg = c.fg },
    ["@variable.builtin"]         = { fg = c.purple, italic = true },
    ["@variable.parameter"]       = { fg = c.orange, italic = true },
    ["@variable.member"]          = { fg = c.orange },
    ["@comment"]                  = { fg = c.comment, italic = true },
    ["@comment.error"]            = { fg = c.red },
    ["@comment.warning"]          = { fg = c.orange },
    ["@comment.note"]             = { fg = c.cyan },
    ["@comment.todo"]             = { fg = c.cyan, bold = true, reverse = true },
    ["@markup.strong"]            = { fg = c.orange, bold = true },
    ["@markup.italic"]            = { fg = c.yellow, italic = true },
    ["@markup.strikethrough"]     = { fg = c.fg, strikethrough = true },
    ["@markup.underline"]         = { fg = c.fg, underline = true },
    ["@markup.heading"]           = { fg = c.purple, bold = true },
    ["@markup.link"]              = { fg = c.fg, underline = true },
    ["@markup.link.uri"]          = { fg = c.cyan, underline = true },
    ["@markup.link.label"]        = { fg = c.pink },
    ["@markup.raw"]               = { fg = c.green },
    ["@markup.list"]              = { fg = c.cyan },
    ["@tag"]                      = { fg = c.cyan },
    ["@tag.delimiter"]            = { fg = c.fg },
    ["@tag.attribute"]            = { fg = c.green, italic = true },
    ["@diff.plus"]                = { fg = c.green },
    ["@diff.minus"]               = { fg = c.red },
    ["@diff.delta"]               = { fg = c.orange },

    -- Git (diff)
    diffFile    = { fg = c.green },
    diffNewFile = { fg = c.red },
    diffAdded   = { fg = c.green },
    diffRemoved = { fg = c.red },
    diffLine    = { fg = c.cyan, italic = true },

    -- gitsigns.nvim
    GitSignsAdd      = { fg = c.green },
    GitSignsChange   = { fg = c.orange },
    GitSignsDelete   = { fg = c.red },
    GitSignsAddLn    = { fg = c.green },
    GitSignsChangeLn = { fg = c.orange },
    GitSignsDeleteLn = { fg = c.red },
    GitSignsAddNr    = { fg = c.green },
    GitSignsChangeNr = { fg = c.orange },
    GitSignsDeleteNr = { fg = c.red },

    -- nvim-cmp
    CmpItemAbbrDeprecated    = { fg = c.red, strikethrough = true },
    CmpItemAbbrMatch         = { fg = c.cyan },
    CmpItemAbbrMatchFuzzy    = { fg = c.cyan },
    CmpItemKindText          = { fg = c.fg },
    CmpItemKindMethod        = { fg = c.green },
    CmpItemKindFunction      = { fg = c.green },
    CmpItemKindConstructor   = { fg = c.cyan },
    CmpItemKindField         = { fg = c.orange },
    CmpItemKindVariable      = { fg = c.purple, italic = true },
    CmpItemKindClass         = { fg = c.cyan },
    CmpItemKindInterface     = { fg = c.cyan },
    CmpItemKindModule        = { fg = c.yellow },
    CmpItemKindProperty      = { fg = c.pink },
    CmpItemKindUnit          = { fg = c.fg },
    CmpItemKindValue         = { fg = c.yellow },
    CmpItemKindEnum          = { fg = c.pink },
    CmpItemKindKeyword       = { fg = c.pink },
    CmpItemKindSnippet       = { fg = c.fg },
    CmpItemKindColor         = { fg = c.yellow },
    CmpItemKindFile          = { fg = c.yellow },
    CmpItemKindReference     = { fg = c.orange },
    CmpItemKindFolder        = { fg = c.yellow },
    CmpItemKindEnumMember    = { fg = c.purple },
    CmpItemKindConstant      = { fg = c.purple },
    CmpItemKindStruct        = { fg = c.pink },
    CmpItemKindEvent         = { fg = c.fg },
    CmpItemKindOperator      = { fg = c.pink },
    CmpItemKindTypeParameter = { fg = c.cyan },
    CmpItemMenu              = { fg = c.comment },

    -- Telescope
    TelescopeBorder         = { fg = c.comment },
    TelescopePromptBorder   = { fg = c.comment },
    TelescopeResultsBorder  = { fg = c.comment },
    TelescopePreviewBorder  = { fg = c.comment },
    TelescopeMatching       = { fg = c.cyan },
    TelescopeSelection      = { bg = c.selection },
    TelescopeSelectionCaret = { fg = c.pink, bg = c.selection },

    -- Which-key
    WhichKey          = { fg = c.cyan },
    WhichKeyGroup     = { fg = c.purple },
    WhichKeyDesc      = { fg = c.pink },
    WhichKeySeparator = { fg = c.comment },

    -- Indent-blankline
    IblIndent     = { fg = c.bglight },
    IblScope      = { fg = c.comment },

    -- Flash
    FlashBackdrop = { fg = c.comment },
    FlashLabel    = { fg = c.bg, bg = c.pink, bold = true },
  }

  return groups
end

return M
